name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'chartoon-networth'
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Prune Dev Dependencies
        run: npm prune --production

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true

      - name: Configure Azure App Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          app-settings-json: |
            [
              {
                "name": "KITE_API_KEY",
                "value": "3xocdwcvyuyp241k",
                "slotSetting": false
              },
              {
                "name": "KITE_API_SECRET",
                "value": "jtlx7xvj3wnxo0k31pd1389x3z83o1uh",
                "slotSetting": false
              },
              {
                "name": "REAL_TRADING",
                "value": "false",
                "slotSetting": false
              },
              {
                "name": "TZ",
                "value": "Asia/Kolkata",
                "slotSetting": false
              },
              {
                "name": "WEBSITE_TIMEZONE",
                "value": "Asia/Kolkata",
                "slotSetting": false
              },
              {
                "name": "FRONTEND_URL",
                "value": "https://chartoon-networth-fe.vercel.app",
                "slotSetting": false
              }
            ]
          general-settings-json: '{"alwaysOn": "true"}'

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: .